// SPDX-License-Identifier: MIT
/**
 * ecosystem.task.v1
 *
 * The single source of a run. run_id is created here and must never be
 * regenerated by any later phase. Workers and gates only pass it through.
 */
import crypto from 'node:crypto'

export const CONTRACT_ID = 'ecosystem.task.v1'
export const DEFAULT_MAX_ATTEMPTS = 2

export function create({
  run_id = crypto.randomUUID(),
  task,
  repository,
  attempt = 0,
  max_attempts = DEFAULT_MAX_ATTEMPTS,
  created_at = new Date().toISOString(),
} = {}) {
  return {
    contract: CONTRACT_ID,
    run_id,
    task: String(task ?? ''),
    repository: repository == null ? null : String(repository),
    attempt,
    max_attempts,
    created_at,
  }
}

export function validate(value) {
  const issues = []
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return { ok: false, issues: ['task must be an object'] }
  }
  if (value.contract !== CONTRACT_ID) issues.push(`contract must be ${CONTRACT_ID}`)
  if (typeof value.run_id !== 'string' || value.run_id.trim().length === 0) issues.push('run_id must be a non-empty string')
  if (typeof value.task !== 'string' || value.task.trim().length === 0) issues.push('task must be a non-empty string')
  if (value.repository !== null && value.repository !== undefined && typeof value.repository !== 'string') issues.push('repository must be a string or null')
  if (!Number.isInteger(value.attempt) || value.attempt < 0) issues.push('attempt must be a non-negative integer')
  if (!Number.isInteger(value.max_attempts) || value.max_attempts < 1) issues.push('max_attempts must be a positive integer')
  if (typeof value.created_at !== 'string' || Number.isNaN(Date.parse(value.created_at))) issues.push('created_at must be an ISO timestamp')
  return { ok: issues.length === 0, issues }
}
