import fs from "node:fs/promises"
import path from "node:path"
import { mergeManagedSections } from "./merge.mjs"
import { ensureParentDirectory, pathExists, readTextIfExists } from "./paths.mjs"

const USER_ACTION_CONTRACT = `## Abschlussvertrag

Jeder deutsche Schlussbericht endet mit \`## Erforderliche Aktion durch den Nutzer\`.
Der Abschnitt enthält ausschließlich durch Capability-, Authentifizierungs-,
Berechtigungs-, Autorisierungs- und Agentenprüfung belegte, nicht delegierbare
Handlungen. Zulässige Reason Codes: \`PHYSICAL_ACTION_REQUIRED\`,
\`RESOURCE_UNREACHABLE\`, \`MISSING_PERMISSION\`, \`MISSING_AUTHORIZATION\`,
\`NON_DELEGABLE_OWNER_APPROVAL\`, \`PERSONAL_LEGAL_DECISION\`,
\`MANUAL_SECURITY_CONFIRMATION\`. GitHub-Aktionen verwenden \`github_web\` mit
nummerierten sichtbaren UI-Schritten, Bestätigung und Abbruchbedingung. Sind
keine Handlungen nötig, lautet der Inhalt exakt:
\`Keine Aktion durch den Nutzer erforderlich.\`
`

const MANAGED_MARKDOWN = `# Hermes Project Bootstrap

## Role Split

- OpenCode remains the primary coding executor.
- Hermes acts as the gateway, orchestrator, and skill runtime.
- MCP access stays disabled until explicitly reviewed.

## Portable Assets

- \`.hermes.md\` carries the project handoff.
- \`.hermes/skills/\` holds reusable skill bundles.
- \`.hermes/bundles/\` lists named skill bundles.
- \`.hermes/mcp/\` holds optional MCP gateway notes.

## Start Guidance

Use Hermes explicitly with the selected skills bundle. Do not rewrite the global Hermes home directory automatically.

## Safety

- no blind overrides
- no prod writes
- no automatic remote CI
- no uncontrolled package installation

${USER_ACTION_CONTRACT}
`

const MANAGED_README = `# Hermes Bootstrap Assets

This directory contains portable Hermes project assets generated by the bootstrap.

## Contents

- \`skills/\`
- \`bundles/\`
- \`mcp/\`

## Notes

Import or copy these assets into Hermes only after review. The bootstrap keeps the global Hermes home directory untouched.

${USER_ACTION_CONTRACT}
`

export function buildHermesRootMarkdown() {
  return MANAGED_MARKDOWN
}

export function buildHermesReadmeMarkdown() {
  return MANAGED_README
}

export function buildHermesBundle(manifestName, skills, notes = []) {
  return {
    version: "1.1.0",
    name: manifestName,
    description: "Portable Hermes bundle for the universal OpenCode bootstrap",
    skills,
    notes,
    activation: {
      default: "disabled",
      requires_manual_review: true,
    },
    completion_contract: {
      schema: ".opencode/validation/schema-validators/user-action-handoff.schema.json",
      language: "de",
      section_title: "Erforderliche Aktion durch den Nutzer",
      empty_message: "Keine Aktion durch den Nutzer erforderlich.",
      actions_field: "actions",
      github_platform: "github_web",
    },
  }
}

export function buildHermesGatewayNote() {
  return `# OpenCode to Hermes Gateway

Hermes can expose conversations as an MCP server with:

\`\`\`bash
hermes mcp serve
\`\`\`

Keep this disabled by default. Enable it only when the target project has reviewed the trust boundary and the gateway is explicitly desired.
`
}

export async function mergeHermesMarkdown(existingPath, replacement) {
  const existing = (await readTextIfExists(existingPath)) || ""
  return mergeManagedSections(existing, [replacement])
}

export async function writeHermesBundle(bundlePath, bundle) {
  await ensureParentDirectory(bundlePath)
  await fs.writeFile(bundlePath, `${JSON.stringify(bundle, null, 2)}\n`, "utf8")
}
